# Site settings
title: "FirstEnergy Team 31140"
description: "FIRST Tech Challenge Team Portfolio - DECODE Season 2025-2026"
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.java"
